### ISSUE TITLE
For Ubuntu-22.04, replace prerequisite libffi6 by libffi7 ?

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-hs#822] opened 2023-04-26 19:10 UTC
https://github.com/haskell/ghcup-hs/blob/17ffc459dbc887d90c8d9aa42f96315e0fb29594/docs/install.md?plain=1#L45

Ubuntu 20/22.04 do not have package `libffi6`, this is from 18.04, according to 
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libffi&searchon=names .

Maybe update this prerequisite to `libffi7`?

In the wild:
- https://github.com/andreasabel/gha-test/actions/runs/4812360408/jobs/8567512363

**Comment by hasufell** [comment] 2023-04-27 04:14
Duplicate of https://github.com/haskell/ghcup-hs/issues/777

**Closed** 2023-04-27 04:14 UTC
