### ISSUE TITLE
`ghcup run` is broken on Windows

### ISSUE THREAD

**Issue by jasagredo** [haskell/ghcup-hs#1106] opened 2024-07-18 12:14 UTC
```shell
➜ ghcup whereis ghc 8.10.7
C:\ghcup\ghc\8.10.7\bin\ghc.exe%

➜ ghcup run --ghc 8.10.7 -- ghc --version
[ Warn  ] Removing leftover files in C:\ghcup\trash
[ Info  ] verifying digest of: gs.exe
The Glorious Glasgow Haskell Compilation System, version 9.8.2
```

The system is Windows 11, MSYS2, MINGW64_NT-10.0-22631, in CLANG64 environment, GHCup version 0.1.30.0

**Comment by hasufell** [comment] 2024-07-18 12:38
I can confirm. CCing @fendor since this may likely break VSCode haskell extension for windows users.

**Comment by hasufell** [comment] 2024-07-18 12:40
Notice that this works:

```pwsh
 ghcup run -m --ghc 8.10.7 -- sh -c 'ghc --version'
```

**Comment by hasufell** [comment] 2024-07-18 12:44
Also confirmed that this is a regression: 0.1.22.0 works.

**Comment by hasufell** [comment] 2024-07-18 12:51
Also found the historical bug: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/375

lolz

**Comment by hasufell** [comment] 2024-07-18 12:59
> Also confirmed that this is a regression: 0.1.22.0 works.

Apparently this was wrong and the comment from the historical issue still applies: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/375#note_435793

I am not sure why I never fixed it.

**Comment by hasufell** [comment] 2024-07-18 13:47
Regarding the `cmd.exe` hack, this gives me headache: https://github.com/haskell/process/blob/ead14c27c9bece12bf74ab8e48d29c982c6f99bb/System/Process/Windows.hsc#L424-L430

Copy pasted (see the comment):

```hs
commandToProcess
  :: CmdSpec
  -> IO (FilePath, String)
commandToProcess (ShellCommand string) = do
  cmd <- findCommandInterpreter
  return (cmd, translateInternal cmd ++ " /c " ++ string)
        -- We don't want to put the cmd into a single
        -- argument, because cmd.exe will not try to split it up.  Instead,
        -- we just tack the command on the end of the cmd.exe command line,
        -- which partly works.  There seem to be some quoting issues, but
        -- I don't have the energy to find+fix them right now (ToDo). --SDM
        -- (later) Now I don't know what the above comment means.  sigh.
commandToProcess (RawCommand cmd args)
  | map toLower (takeExtension cmd) `elem` [".bat", ".cmd"]
  = return (cmd, translateInternal cmd ++ concatMap ((' ':) . translateCmdExeArg) args)
  | otherwise
  = return (cmd, translateInternal cmd ++ concatMap ((' ':) . translateInternal) args)
```

**Comment by hasufell** [comment] 2024-07-20 15:50
merged: https://github.com/haskell/ghcup-hs/pull/1108

**Closed by hasufell** 2024-07-20 15:50 UTC
Labels: type: bug, command: run
