### ISSUE TITLE
ghcup v0.1.19.2 fails to install GHC 8.10.7 on NixOS

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/ghcup-hs#813] opened 2023-03-24 07:33 UTC
Logs of the terminal session:

```bash
[runeks@nixos:~]$ NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/release-21.11.tar.gz" nix-shell -p haskellPackages.ghcup

[nix-shell:~]$ ghcup --version
The GHCup Haskell installer, version 0.1.17.3

[nix-shell:~]$ ghcup upgrade
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.6.yaml as file /home/runeks/.ghcup/cache/ghcup-0.0.6.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[ Warn  ] New GHCup version available: 0.1.19.0. To upgrade, run 'ghcup upgrade'
[ Warn  ] New Cabal version available: 3.6.2.0. To upgrade, run 'ghcup install cabal 3.6.2.0'
[ Warn  ] New GHCup version available: 0.1.19.0. To upgrade, run 'ghcup upgrade'
[ Warn  ] New Cabal version available: 3.6.2.0. To upgrade, run 'ghcup install cabal 3.6.2.0'
[ Info  ] Upgrading GHCup...
[ Warn  ] Possibly insufficient disk space on /run/user/1000. At least 5000 MB are recommended, but only 4084.1 are free. Consider freeing up disk space or setting TMPDIR env variable.
[ Warn  ] ...waiting for 10 seconds before continuing anyway, you can still abort...
^C

[nix-shell:~]$ export TMP=/tmp

[nix-shell:~]$ export TMPDIR=/tmp

[nix-shell:~]$ ghcup upgrade
[ Warn  ] New GHCup version available: 0.1.19.0. To upgrade, run 'ghcup upgrade'
[ Warn  ] New Cabal version available: 3.6.2.0. To upgrade, run 'ghcup install cabal 3.6.2.0'
[ Warn  ] New GHCup version available: 0.1.19.0. To upgrade, run 'ghcup upgrade'
[ Warn  ] New Cabal version available: 3.6.2.0. To upgrade, run 'ghcup install cabal 3.6.2.0'
[ Info  ] Upgrading GHCup...
[ Info  ] downloading: https://downloads.haskell.org/~ghcup/0.1.19.0/x86_64-linux-ghcup-0.1.19.0 as file /tmp/ghcup-79be6646af60c682/ghcup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.2M  100 15.2M    0     0  11.0M      0  0:00:01  0:00:01 --:--:-- 11.0M
[ Info  ] verifying digest of: ghcup
[ Warn  ] ghcup is not in PATH! You have to add it in order to use ghcup.
[ Info  ] Successfully upgraded GHCup to version 0.1.19.0

[nix-shell:~]$ export PATH=~/.ghcup/bin:$PATH

[nix-shell:~]$ ghcup --version
The GHCup Haskell installer, version 0.1.19.0

[nix-shell:~]$ ghcup upgrade
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml as file /home/runeks/.ghcup/cache/ghcup-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.10.1.0'
[ Info  ] Upgrading GHCup...
[ Info  ] downloading: https://downloads.haskell.org/~ghcup/0.1.19.2/x86_64-linux-ghcup-0.1.19.2 as file /home/runeks/.ghcup/tmp/ghcup-03673cd09d6e5c00/ghcup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.2M  100 15.2M    0     0  36.9M      0 --:--:-- --:--:-- --:--:-- 36.9M
[ Info  ] verifying digest of: ghcup
[ Info  ] Successfully upgraded GHCup to version 0.1.19.2

[nix-shell:~]$ ghcup --version
The GHCup Haskell installer, version 0.1.19.2

[nix-shell:~]$ ghcup install ghc 8.10.7
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.10.1.0'
[ Info  ] downloading: https://downloads.haskell.org/~ghc/8.10.7/ghc-8.10.7-x86_64-fedora27-linux.tar.xz as file /home/runeks/.ghcup/tmp/ghcup-d7c4e637bc7db41d/ghc-8.10.7-x86_64-fedora27-linux.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  207M  100  207M    0     0  56.2M      0  0:00:03  0:00:03 --:--:-- 56.3M
[ Info  ] verifying digest of: ghc-8.10.7-x86_64-fedora27-linux.tar.xz
[ Warn  ] CC/LD environment variable is set. This will change the compiler/linker
[ ...   ] GHC uses internally and can cause defunct GHC in some cases (e.g. in Anaconda
[ ...   ] environments). If you encounter problems, unset CC and LD and reinstall.
[ Info  ] Unpacking: ghc-8.10.7-x86_64-fedora27-linux.tar.xz to /home/runeks/.ghcup/tmp/ghcup-f0821dd10e8fd60c
[ Info  ] Installing GHC (this may take a while)
[ ghc-make ] /nix/store/i9q0jv6qnvg7zal98rqi7aq31k3p89hw-coreutils-9.0/bin/install -c -m 755 -d  "/home/runeks/.ghcup/tmp/ghcup-7e7...
[ ghc-make ] for i in  rts/dist/build/libHSrts.a rts/dist/build/libHSrts_p.a rts/dist/build/libHSrts-ghc8.10.7.so rts/dist/build/li...
[ ghc-make ] "utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/ghc-prim dist-install "strip" '/home/runeks/...
[ ghc-make ] utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist: line 3: /home/runeks/.ghcup/tmp/ghcup-f0821dd10e8fd60c/ghc-8...
[ ghc-make ] make[1]: *** [ghc.mk:984: install_packages] Error 127
[ ghc-make ] make: *** [Makefile:51: install] Error 2
[ Error ] [GHCup-00841] Process "make" with arguments ["DESTDIR=/home/runeks/.ghcup/tmp/ghcup-7e71464457d1de93",
[ ...   ]                                "install"] failed with exit code 2.
[ Error ] Also check the logs in /home/runeks/.ghcup/logs
```

Full logs:

[ghc-configure.log](https://github.com/haskell/ghcup-hs/files/11059514/ghc-configure.log)
[ghc-make.log](https://github.com/haskell/ghcup-hs/files/11059515/ghc-make.log)
[ghcup.log](https://github.com/haskell/ghcup-hs/files/11059516/ghcup.log)

**Comment by hasufell** [comment] 2023-03-24 07:35
Nothing new or surprising. 

There are no bindists built specifically for NixOS. I don't know how that would work even.

**Comment by hasufell** [comment] 2024-01-26 09:03
duplicate of https://github.com/haskell/ghcup-hs/issues/184

**Closed by hasufell** 2024-01-26 09:03 UTC
Labels: scope: upstream, status: help-needed, type: improvement
