### ISSUE TITLE
ghcup tui command fails after a brief amount of time on Windows 11

### ISSUE THREAD

**Issue by VitorCBSB** [haskell/ghcup-hs#1014] opened 2024-02-29 21:07 UTC
This is a puzzling one as I'm sure `ghcup tui` was working just fine at some point, but as of now the following happens:

1. Call `ghcup tui` on `cmd`;
2. Terminal UI loads up and is shown for about a second or so;
3. UI abruptly closes with the following:
```
PS C:\Users\Vitor> ghcup tui
[ Info  ] verifying digest of: gs.exe
ghcup.exe: thread blocked indefinitely in an STM transaction
```

I'm honestly blaming this on some Windows update, but I felt it would be better to open this issue just so you are aware as well. Let me know if I can help with this somehow.

OS specs:
Microsoft Windows 11 Pro
Version 10.0.22621

**Comment by hasufell** [comment] 2024-03-01 02:49
https://github.com/jtdaugherty/brick/issues/502

**Comment by hasufell** [comment] 2024-03-01 02:50
Duplicate of https://github.com/haskell/ghcup-hs/issues/1013

**Closed** 2024-03-01 02:50 UTC
Labels: scope: upstream, type: bug
